- data.js
> added my blog post too, Vlad Pasca

- components/TheFooter.vue
> Aadhithyan Blog

- data.js
Follow the guidelines and added everything accordingly.
> Daily dev tips

- data.js
> Add codebycorey

- data.js
> Adding blog: dannys.cloud

- data.js
> Added Blog - rams.codes

- data.js
Here is my entry 💜 Awesome project and good tech choice, love it!! 🤗
> Add Alba Silvente Blog

- data.js
Adding my blog to the repository.
> Adding Sunil Kumar's blog

- data.js
> Add Alexander Lichter's Blog

- data.js
> Add Victoria Lo

- data.js
Adding my blog to the repository.
> Add Harris Geo's blog

- data.js
> Add Code Create blog

- data.js
> Add Scott Spence

- data.js
> Rename React.js to React

- data.js
> Add codepunkt.de blog

- data.js
> Adds impure.fun

- data.js
> Add Nilanth Blog

- data.js
> added Stefan Natter

- data.js
https://blog.idrisolubisi.com/
> Updated data with my blog(https://blog.idrisolubisi.com/) details

- data.js
Signed-off-by: Franklin <franklinokolie86@gmail.com>
> Added DeveloperAspire Blog

- data.js
> Add Aman Mittal's Blog

- data.js
> Add WP Owls blog

- data.js
Confirmed all PR template requests! 
Thanks for creating this.
> Add Adrienne Tacke Blog

- data.js
> Add sld.codes

- data.js
> Added Abiola Farounbi Blog

- data.js
> Adding Blog- Ankur Tyagi

- data.js
Happy to be listed on your website. :)
> Add Jiri Tichy Blog

- data.js
Added my blog
Just adding myself and my blog :+1: 
Marko is awesome <3
> Add Alexander Rowsell Frozen Electronics

- data.js
add my blog to this awesome list!
> Add Victor Meunier blog

- data.js
> Added Mattou07 Blog

- data.js
> Add Saad Ahmad Blog

- data.js
> Add Murewa Ashiru blog

- data.js
> Add Puru Vijay Blog

- data.js
Added https://webdevjeet.me. 
let me know if changes are required
> Add Web Dev Jeet Blog

- data.js
> Add Varun Singh Blog

- data.js
> Add Dotneteers Blog

- data.js
> Add Steven Spad's blog

- data.js
> Added apludwebmaker to data.jd

- data.js
> Add learnedia to the list

- data.js
> Add Umair Hafeez Blog

- data.js
> Add Sebastian Hesse Blog

- data.js
> Added My profile to the list

- data.js
> add devopsian blog

- data.js
> Add Sebastian Urban Blog

- data.js
> Add Your Name Blog - Rahul

- data.js
> Add Your Name Blog

- assets/less/app.less
- babel.config.js
- components/Blog.spec.js
- jest.config.js
- package.json
- pages/index.spec.js
- pages/index.vue
- yarn.lock
**Unit testing**
**Number of blogs by tag** - #78
> Add unit test Jest configuration and number of blogs by tag

- data.js
Added my own little programming blog
> Update to add http://sunriseprogrammer.blogspot.com/

- data.js
> Add KEJK | Thoughts blog

- data.js
> Add Silvestar Bistrović Blog.

- data.js
> Add Albertwalicki.com blog

- data.js
> Added my blog link

- data.js
This PR adds https://codeperf.io, a blog focused on code optimisation, monitoring, and observability methodologies.
> Add codeperf.io

- data.js
Added my blog etc. following the guideline.
> Add Stephan Kämper Blog

- data.js
> Add Sakun Pushpitha blog

- data.js
> Add augustoproiete.net

- data.js
Added Phil McParlane (https://4dayweek.io/blog)
> Added 4 Day Week blog

- data.js
Added by blog: https://dunglas.fr
> Add Kévin Dunglas's blog

- data.js
Added Rishab Kumar's tech blog
> Added Rishab Kumar's tech blog

- data.js
> Added Create React App tech blog

- data.js
> Add Unicorn Utterances Blog

- data.js
> Add Preston Lamb

- data.js
> Add Alberto Bonacina Blog

- data.js
Not my blog, but an absolute must for SVG tips and tricks and all things Vue 💕
> Add Sarah Drasner Blog

- data.js
I might be wrong on the description. I just copy-pasted my Medium bio. If you'd like me to change it, I'm good with that.
> Add my Medium page (blog?)

- data.js
My personal blog available at https://jarmos.netlify.app where I write about programming, Machine Learning & Python as a self-taught developer.
> Add Somraj Saha's blog

- data.js
> add tshiteej blog

- data.js
> <OhMyScript/> Blog

- data.js
> Added Bharadwaj details.

- data.js
> Blog link update

- data.js
> Add marcelhauri.ch

- data.js
> Add mokkapps.de

- data.js
> Add William Chin's Blog

- data.js
PR for [my personal blog](https://dillionmegida.com/blog)
> Add Dillion Megida blog

- data.js
[ThisDot Blog](https://labs.thisdot.co/blog)
> Add ThisDot Blog

- data.js
> Add Adithya Blog

- data.js
Patch to add additional frameworks
> Updated Karl Koch

- data.js
> Add Nacho Iacovino blog

- data.js
> Add Ravgeet Blog

- data.js
> Add "The Trojan" Blog

- data.js
Removed 404 url ( rams.codes ) and updated with current one ( ramyachinnadurai.in )
> Update - Ramya Chinnadurai url 

- data.js
Added my blog site to the list
> Added Shyam's blog

- data.js
@markodenic Please don't forget to add `hacktoberfest-accepted` label. Thanks!
> Add Sushmita's Blog

- data.js
Hey 👋 
I just added my blog to the list :)
> Added my blog 

- data.js
> Added Michael Asiedu@asiedu_dev blog

- data.js
> Added Software Pragmatism

- data.js
> Updated my blog domain.

- data.js
Add [My Blog](https://frankiefab.hashnode.dev)
> Add Frankiefab.hashnode.dev

- data.js
> Add Goodness Ezeh's blog

- data.js
> Add Greenroots blog(tapas adhikary)

- data.js
> Add Ozer Tayiz Blog

- data.js
> Add Osama Mohamed Blog

- data.js
> Added LambdaTest blog

- data.js
> Adds soliditytips.com

- data.js
> Add Leon AI Blog

- data.js
Added details for my tech blog.
> Added Ivan Kahl's Blog

- data.js
> Add Bob Fornal's Blog

- data.js
> Add Ashish Yadav's Blog

- data.js
> added-pankaj-patel

- data.js
UnEncrypted is Reda BELHAJ's Blog
> Add UnEncrypted Blog

- data.js
Added Mick Patterson Blog details to data.js
> Add Mick Patterson Blog

- data.js
> Add Roberto's Blog

- data.js
> update data with my blog

- data.js
@markodenic Please add my blog to awesome tech blogs.
> Add Sachin Chaurasiya Blog

- data.js
> Add Niraj Khatiwada's Blog

- data.js
> Adding my blog to the list

- data.js
> Add Sagar Paul Blog

- data.js
> add Avneesh Agarwal

- data.js
> Add Omar Elhawary Blog

- data.js
> Adding Margo McCabe's Blog

- README.md
> Add instructions on how to add a new blog

- data.js
I have added my blog details to data.js file.
> Add Rajanand Ilangovan's blog

- data.js
> Add AlterClass blog

- data.js
https://www.webdevolution.com 
Webdevolution - Blog about web development
> Add Webdevolution

- data.js
> Add Vivek Blog

- data.js
> Add Renan Moura's Blog

- data.js
> Add Sandro's Blog

- data.js
Good work. Saw you guys on product hunt.
> Add TerminusDB blog

- data.js
> updated me

- data.js
Add Priyanshu Kumawat's Blog to Awesome Tech Blogs
> Add Priyanshu Kumawat Blog

- data.js
> Add Seth Michael Larson's blog

- data.js
> add Estee Tey's Tech Blog

- data.js
> Add AutoSysOps

- data.js
> Add Wysr Blog

- data.js
> Add Dan Kazimoto blog - UI designer and content creator

- data.js
> Add blog for @rajkbnp

- data.js
> added All-in-One Person

- data.js
> Add FlutterBeads - https://flutterbeads.com/ - A treasure of high quality Flutter tutorials

- data.js
Read mostly about web development, tools that help you finish the job faster, also algorithms, data structures, and occasionally tips&tricks, along with funny projects. Welcome to Bllog | by kaumnen.
> add Aleksej Komnenovic blog

- data.js
Adding here Stefan's blog fettblog.eu which is IMHO a go-to resource for
TypeScript and Rust lately.
> Add Stefan Baumgartner's blog

- data.js
Coderflex it's a `tech blog` has the following topics:
- Laravel News, Tutorials
- Laravel Livewire 
- Linux Blog Posts
- Web Security
- JavaScript
- Web dev advices
- Open source projects
> Add coderflex.com blog

- data.js
> Added techwithsidz blog address with data content tags

- data.js
Added canopas software blog according to guideline.
> Add Canopas Software Blog

- data.js
> Added Madza's blog

- data.js
> data js added random

- data.js
> Started a new blog site. Added the info.

- data.js
> Add Pritam's Blog

- data.js
Adding my personal blog https://mustafa.page/ to the list of tech blogs
Thanks
Mustafa
> Adding mustafa.page blog

- data.js
:wave: Hello,
I'm Vinit Shahdeo, a Software Engineer, currently working at Postman. I write about open-source, JavaScript, my journey into tech and things in between.
> View my blog: https://vinitshahdeo.dev/
> Add `git [w]init` 

- data.js
Added the [Webiny blog](https://www.webiny.com/blog/) link, we post about severless, CMS, DevOps and around JavaScript ecosystem.
> Add Webiny Blog

- data.js
> Added HeadSpin

- data.js
> Add Namya's blog

- data.js
> Add gokul.site blog to list

- data.js
Adds my blog Sailing the Sharp Sea. I write about C#, Xamarin, .NET MAUI and GitHub Actions.
Thanks.
> Add Sailing the Sharp Sea blog

- data.js
> Add Sabe.io

- data.js
> feat: ➕ add blog.beraliv.dev

- data.js
> Add shubhambattoo.in/blog

- data.js
Updated!
Added my own blogging website
> Updated data.js

- data.js
> Add zachjonesnoel blog

- data.js
> Added my hashnode blog

- data.js
> add Roopesh Sn's Blog

- data.js
> added new blog - how javascript works

- data.js
> feat(suprabha): adding suprabha's blog

- data.js
> Add Bleyl Dev Blog

- data.js
> Andrew Baisden profile

- data.js
> Add Elton Minetto's blog

- data.js
> Add Alessandro Marino blog

- data.js
> Add fadhil-blog.dev

- data.js
It is about web development, programming, and technology-related tips and guides.
> Adds Dev Apt blog

- data.js
TestingBot's blog contains information on test automation.
> Add TestingBot blog

- data.js
> Add learnersbucket

- data.js
> Added my blog

- data.js
> Update Twitter Username for iRead Blog

- data.js
> Add blog vivekjaiswal.me

- data.js
> Added TestGrid

- data.js
Not my blog but an important tech blog not yet included in collection!
> "Add Your Name Blog"

- data.js
> Add duyet.net

- data.js
I have just added my blog - Mbaziira Ronald's blog https://mbaziira.hashnode.dev
> Added my blog - Mbaziira Ronald's blog

- data.js
> Add Myself

- data.js
I would love to have my blog shown on your awesome website Tech Blogs 🙏
> Add blog name DevByRayRay 

- data.js
> Updated Blog

- data.js
> Add Tim Mousk Blog

- data.js
> Add toidicode.com blog

- data.js
> added Chris Achinga Tech blog

- data.js
> Snehasish Chakraborty, add blog related to HSTS

- data.js
> added my first open source input

- data.js
> add golang.ch

- data.js
> Added Aman Panjwani Blog

- data.js
Added more keywords and descriptions into the title card for more precise search. 
Ref : https://github.com/markodenic/awesome-tech-blogs/pull/334#issue-1286146780
> Updating the portfolio - Tauqeer

- data.js
> adding blog

- data.js
- added [syntackle.live](https://syntackle.live) blog
> Add Murtuzaali Surti's Blog - Syntackle

- data.js
> added blogs details

- data.js
> Added www.yonasuriv.com

- data.js
> Add Adit Modi's Tech blog related data

- data.js
> Added yonasuriv.com

- data.js
Reverts markodenic/awesome-tech-blogs#350
The blog already exists.
> Revert "Added yonasuriv.com"

- data.js
> Add DevTales Blog

- data.js
> add masteringbackend tech blog

- data.js
> Add maxkovalevsky.com

- data.js
> add 2minsDevsNotes to awesome-tech-blogs

- data.js
> Add livecodestream dev to the list of awesome tech blogs

- data.js
> Added portfolio Vincenzo

- data.js
> Add Anil Rao K

- data.js
> Add codedamn Blog

- data.js
> Add teco tutorials blog

- data.js
> Add Kyle Platt Blog

- data.js
[X] - Ensure you are linking to a blog page, not to your front-page, except your front-page is your blog page. :)
[X] - Ensure you're writing about tech.
[X] - Ensure you're using single quotes for property values.
[X] - Ensure you added yourself somewhere random, and not at the end of the file, so we avoid merge conflicts.
[X] - Ensure your data is formatted like other entries.
[X] - Add up to 10 tags!
[X] - Ensure this PR has a title in the following format: "Add Your Name Blog"
> Add Engin Arslan and Awesome Coding Blog

- data.js
> Add bitExpert Blog

- data.js
I updated the blog URL for my own entry to https://www.paulsblog.dev. 
The old domain will stay active but will redirect to the new one.
> Update blog url to https://www.paulsblog.dev

- data.js
> Add Christine’s Blog

- data.js
> Add Aleix Morgadas Blog

- data.js
> Add Atharva Salitri's Blog

- data.js
> add Jina AI Blog

- data.js
> add Richard Callaby

- data.js
> Added link to Twitter profile

- data.js
> added rahul.biz

- data.js
> Added Harsh's Blog

- data.js
> Added Argonaut blog

- data.js
> Fixing silvestar.codes domain.

- data.js
> Fix bitExpert Blog url

- data.js
> Add Abhijit Sarode Blog

- .github/workflows/LinkChecker.yml
- data.js
> added Roblog bloging site

- data.js
> Add bmf-tech.com

- data.js
> Add aiherrera Blog

- data.js
> Mastering C++ Templates: A Guide to Creating Your Own Custom Template Library Similar to STL

- data.js
> Add Bryan Braun blog

- data.js
Please add my blog to the list.
Offtopic: Thank you for creating this resource. Found quite a few cool blogs I would have a 0% chance of finding otherwise!
> Add devprogrammer.com Blog

- data.js
> Add Guillaume Briday blog

- data.js
I will blog about general code quality improvements/monitoring here. Also refactoring techniques and workflows, how to deal with legacy code, etc.
> Add Attractor Blog

- data.js
> Add (name update) Devopsian blog

- data.js
> Add ajxs.me

- data.js
> Add my personal blog

- data.js
> add globaldatanet blog

- data.js
Added my record and formatted data.js file
`
{
name: "Renuka Cheripally",
description: "Frontend Vue js developer. Expanding my professional network and contributing to open source projects",
url: "https://github.com/RenukaCheripally",
twitter: "@renukach170397",
tags: [
"HTML",
"CSS",
"JavaScript",
"TypeScript",
"Vue js",
"Web Development",
"Front End",
"Back End",
"Freelancing",
"Java",
"SQL",
],
},
`
> Added my record

- data.js
> Add qajobs blog

- data.js
> Add Teotime Pacreau Blog

- data.js
> Add Jakub T. Jankiewicz Blog

- data.js
> Add tech blog tderflinger.com

- data.js
Adding Don't Break Prod
https://dontbreakprod.com/
(I used double quotes because there's a single quote in the blog name...)
> Add Don't Break Prod

- data.js
> Added JPaul.me Blog

- data.js
> Add Christian Tech Jobs Blog

- data.js
> Add Harrison Broadbent Blog

- data.js
Added my website and links (blog page is front page)
> Add Oliver J. Scholten Blog
